export {
  buildExpertInviteText,
  buildMascotReply,
  buildTranscriptReturnMessage,
  createEscalationRequest,
  decideMascotAction,
  detectEscalationNeed,
  normalizeEscalationTopic,
  type CreateEscalationInput,
  type EscalationParticipant,
  type EscalationRequest,
  type EscalationSignal,
  type EscalationStatus,
  type MascotChatMessage,
  type MascotDecision,
  type MascotDecisionAction,
  type MascotDecisionInput,
  type MascotDecisionSource,
  type MascotChatRole,
} from './mascotEscalation.ts';
